language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - build-essential
      - clang
      - cmake
      - bison
      - flex
#
# Compliant with Gazr Specification
# https://gazr.io
# https://github.com/dailymotion/gazr
# make style | test-unit | test-functional | init
script:
  - true
  # - make style
  # - make test-unit
  # - make test-functional
cache: pip
install:
  - make init
  - pip install -e .[test]
deploy:
  provider: pypi
  user: dailymotion-tech
  password:
    secure: VX+vu1/JalKaiQjFzq6P4r2jVCmA3vD4+7jqdgaQProklvImiVK+aGuDeXoXs0e1hY7cvkTlhpZJdpxFx89yHNRnuanTMggs4L+6jAhiaB7/gh0HZg9Sc3DEr1XpugkqlRahF1d6tgkdY47veiH8DSsRUPzsiNXTOlzkbH5DqzDe7hQ5lJTbdiJyq30Uu3x6rbsA/CUCjB+BTUTPv5OBKFW/COPjrSxptBSJXuKVMP1/DwiAqSEPudroaja6daYRHN6vtLaPb0UAPCDnGpbgxlR73isM7YClW+Adr3QrbQ8EyAre+Z6vq69Tkl7TLh1Hlrf/P9RcHn1gqTJEcfaOZwJTuj8i34tLvEFKhkz1wjM8FpHgZeiJzK0oewV/ydJu39EaH2RuRPn4SRJPv2p42oGC+GMLh/oMw5uviU6J3uVJVJzaya4PBKl/LGP7FMimtwHcT2Vq8Xm4IAzGa9an3+kb4nUi9k+iWHQUUpcwKzpoaAusoyajz443cQSbaCMlpaXx2hlUcxIkttpGXKr2dw+WpF6efhq/6Kw+I6XJg7EaMQmbikpRYs3hhvUZpM8XNDs+07FRXpQop3jlMwVekRLP+1bOB4vlD4XJ0SzFKTLNLO6851vZp24QDFzaLcqQkrb+GSkPa+x667sbTW0u7zPC4WpjFsTvypopG6t6xuc=
  on:
    branch: master
