language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - build-essential
      - clang
      - cmake
      - bison
      - flex
#
# Compliant with Gazr Specification
# https://gazr.io
# https://github.com/dailymotion/gazr
# make style | test-unit | test-functional | init
script:
  - make test-unit
  - make test-functional
  # - make style
cache: pip
install:
  - make init
  - pip install -e .[test]
deploy:
  provider: pypi
  user: dailymotion-tech
  password:
    secure: Qg3c8iFRx4dB+vNaz/WgETK4i5jDFeRy+7liOBkgZHuYByTlC4TeMG7l19J+xQpTsCD5ZLaYqaA5YaldsTkQ2G5hCPhk7ULCv1SQXZmzl7c5UQ+2H22tW3KzI7cFfsWlYya8ItaayTE+HfYGLjZTvr+UCh4Td3Ea4xxTNk/cfgpdsOMpEFOWjHWlCtQsg8iT4Rv+VSokflyU+tSK4ibr76Deg7X3DTldKO3FpiQCyDSd2HzsCaAG03OCL7qSmmWsvzF8BLj+KntJNbINENJVXHATe88pXZe80vEe7/QTo6q24zdPIzVm2/BOqybconNN1jLJVogYeI7cu2BzRYtZJVzPEFDBu9QHX7aZC2zIgIDOWHidh+lxYx8FxpMVtFGfjWlx1Eq3OcypyYqIQhy6+BoJqOgfMoO+r3ANCjYsQksfWT6Wd/hTvF8/97zuZlF4n8tZhlBYmYZZ5BcJhuRgkydEHDKwNvH9ROyv4clM/iAiGTd7h7Plwt4jdDZU2XAVF5XZFxrrWVNx8ZqbDQNkCE2yIhnikNDWkAcX2PA/2u9rWNDtLjuNeMw5NZRum0lgdlrBU+6oDF7OZgzedCY2XrRF/D64JGVyUCCl3MK2xsvCBv4n6SekML0dzsmn6CO0NgdERU0fr+1zdvllfuOTwkvh7UHSUEgQ2+IUqhKWu4k=
  on:
    branch: master
