language: python
python:
  - "3.6"
addons:
  apt:
    packages:
      - build-essential
      - clang
      - cmake
      - bison
      - flex
#
# Compliant with Gazr Specification
# https://gazr.io
# https://github.com/dailymotion/gazr
# make style | test-unit | test-functional | init
script:
  - true
  # - make style
  # - make test-unit
  # - make test-functional
cache: pip
install:
  - make init
  - pip install -e .[test]
deploy:
  provider: pypi
  user: dailymotion-tech
  password:
    secure: wRH5U7Z3mW+7KsEfeu+FEljPFV6WGkm8NVuAmndGcVuDyk9hUGgZ26LD8zxcecqBIN6wNH0rvXvxjnpR/eGIdk4w8HHGbyVi608BKaQNuJjm/SQUpzs/K3kJywwPPxq/MSun7j5V5ZvWia/DEd1x2lA/PguEdUbm2NDXXtI6M+R2NYDmkJ3q9dPkK1YWTdRc4HQ7bBVSoh3+D7SE78/OZt8+D5AZC4zdPBHBcoBamor6ob+V/10eXLWX8MIG8iQ+Uk9EQ2phjATaFa1sSQXMn15+8b8B74vDssP/aRhyVIzp0yLQfWXocdF+xUYokyzOqdyrt3rp8r8PjCXe+ti7ycSwg9vqSpIxaQYyL9HFwp+ttTa5cGG83jIh7EUxVtHce+jlUFALb9O6USEj0wYGHstjQvLAFwYWD9qS38Rpw0j//my6c+jFYTSv7XfBsWxAONZ55wKg314boxkZ8hYu/+rRF4wNwAmdtu1I8jE5+ufbD+eQpFqFjgvLTBTWSKyPsVEmhnHdrxCLlK0h+VRPDTqCqZhM39SnreCLMMhqBiq5QpNscKY5U9Aq3RUDyBv2zH8HtK9CUKGISyBqBVMAni7J+/alyVMoVQgKKIF4f33uhj0pgPsuawCOQyXcO05A6jezzHZzDBJrU/nKf7kVF+Az7KxINEL3lomSnDAoqfQ=
  on:
    branch: master
