name: Validate PullRequest
on: [pull_request]
jobs:
  Style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: style
        uses: ./
        with:
          args: make style
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: functional test
        uses: ./
        with:
          args: make test-functional
      - name: unit test
        uses: ./
        with:
          args: make test-unit
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Unshallow
        run: git fetch --unshallow
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  PublishToPypiDev:
    runs-on: ubuntu-latest
    needs:
      - Tests
      - Style
      - SonarCloud
    steps:
      - uses: actions/checkout@master
      - name: build and publish to pypi
        uses: ./.github/actions/pypi/
        if: github.ref != 'refs/heads/master'
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
