name: Validate PullRequest
on: [pull_request]
jobs:
  Style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: style
        uses: ./
        with:
          args: make style
  TestsUbuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
      fail-fast: true
    steps:
      - uses: actions/checkout@master
      - name: Set Python Version ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Deps
        run: sudo apt update && sudo apt install cmake bison flex && make init && pip install -e .[test]
      - name: Functional Tests
        run: make test-functional
      - name: Unit Tests
        run: make test-unit
  TestsMacos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.6, 3.7, 3.8]
      fail-fast: true
    steps:
      - uses: actions/checkout@master
      - name: Set Python Version ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Deps
        run: brew install cmake flex bison && make init && pip install -e .[test]
      - name: Functional Tests
        run: make test-functional
      - name: Unit Tests
        run: make test-unit
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Unshallow
        run: git fetch --unshallow
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  PublishToPypiDev:
    runs-on: ubuntu-latest
    needs:
      - TestsUbuntu
      - TestsMacos
      - Style
      - SonarCloud
    steps:
      - uses: actions/checkout@master
      - name: build and publish to pypi
        uses: ./.github/actions/pypi/
        if: github.ref != 'refs/heads/master'
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
