name: Build'n'Release

on:
  push:
    branches: [ master ]

jobs:
  Style:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - name: Setup Python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
      - name: Install Python dependencies
        run: pip install -e .[test]
      - run: make style
  Tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - name: Setup Python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
      - name: Install Python dependencies
        run: pip install -e .[test]
      - name: Functional Tests
        run: make test-functional
      - name: Unit Tests
        run: make test-unit
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init
      - name: Unshallow
        run: git fetch --unshallow
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  PublishAndRelease:
    runs-on: ubuntu-20.04
    needs:
      - Tests
      - Style
      - SonarCloud
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Pypi
        uses: ./.github/actions/pypi/
        if: github.ref == 'refs/heads/master'
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      - name: Set Version and Changelog
        uses: ./.github/actions/shell/
        if: github.ref == 'refs/heads/master'
        with:
          entrypoint: make
          args: github-action-version-and-changelog
      - name: Creates Github Release
        uses: ./.github/actions/release/
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: tartiflette
          USERNAME: tartiflette
